### PR TITLE
Fangtong/hw1

### PR DESCRIPTION
**Pull request by cube12138**
Not sure whether the maven module is right

### CODE REVIEW

**Comment by TheSwaggyOne** [comment]
I like your MD format, better than mine!

**Comment by AllenLXL** [comment]
lgtm

**Comment by krystaZeng** [comment]
Nicely Done! It is ready to merge!

**Comment by Liam-Zhou** [comment]
good but  no mk usage instruction file

**Comment by jindajia** [comment]
good

**Pull request merged**
